name: "Release Scheduler"
description: "GitHub Actions starter for TypeScript with automated releases"
author: "Koj <https://github.com/koj.co>"
inputs:
  token:
    required: false
    description: "GitHub token"
  filePath:
    required: false
    description: "File to commit to"
    default: "package.json"
  minimumCommits:
    required: false
    description: "Minimum number of Dependabot commits required"
    default: "1"
  commitMessage:
    required: false
    description: "Semantic release commit message"
    default: ":package: Release dependency updates"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "wind"
  color: "red"
