name: Release Scheduler Test
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  releaseScheduler:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, ':rocket:')"
    steps:
      - name: Run release-scheduler
        uses: koj-co/release-scheduler@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
